#!/bin/bash
echo "Сборка единого отчёта CI/CD..."

REPORT="report.md"

{
    echo "# Отчёт CI/CD"
    echo ""
    echo "Дата: $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "## Локальные проверки (Git Hooks)"
    echo "- pre-commit: проверка маркеров в staged Python-файлах"
    echo "- pre-push: запуск unit-тестов pytest"
    echo "- commit-msg: проверка формата сообщения (feat/fix/docs/ci/chore/test/refactor)"
    echo ""
    echo "## Jenkins Pipeline"
    echo "- Checkout — клонирование репозитория"
    echo "- Setup Python — python3 --version, pip --version"
    echo "- Install dependencies — установка requirements.txt и requirements-dev.txt"
    echo "- Compilation Check — py_compile server.py voicegen.py model_loader.py"
    echo "- Linting — ruff check ."
    echo "- Проверка маркеров — bash ci-check.sh"
    echo "- Tests — pytest tests/ -v"
    echo ""
    echo "## Артефакты"
    ls -la *.json *.xml *.html *.log 2>/dev/null || echo "нет файлов отчётов"
    echo ""
    echo "## Итог"
    echo "Локальные хуки дают быструю обратную связь (секунды)."
    echo "Jenkins выполняет расширенные проверки (минуты): unit-тесты, security scan, load test."
} > "$REPORT"

cat "$REPORT"
echo ""
echo "report.md сохранён"
